### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by pvandriessche** [bennylope/django-organizations#129]
Hello, 

I'm trying to installing django-organization. I tried usins pip and got the following error.
I'm using the cloud 9 platform with python 1.10
Thanks a lot for the help
`
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 350, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 324, in execute
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/organizations/models.py", line 26, in <module>
    from .abstract import (AbstractOrganization,
  File "/usr/local/lib/python2.7/dist-packages/organizations/abstract.py", line 37, in <module>
    from .base import OrgMeta, AbstractBaseOrganization, AbstractBaseOrganizationUser, AbstractBaseOrganizationOwner
  File "/usr/local/lib/python2.7/dist-packages/organizations/base.py", line 186, in <module>
    class OrganizationBase(six.with_metaclass(OrgMeta, AbstractBaseOrganization)):
  File "/usr/lib/python2.7/dist-packages/six.py", line 617, in with_metaclass
    return meta("NewBase", bases, {})
  File "/usr/local/lib/python2.7/dist-packages/organizations/base.py", line 74, in __new__
    return super(OrgMeta, cls).__new__(cls, name, bases, attrs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 81, in __new__
    module = attrs.pop('__module__')
KeyError: u'__module__'
`

**Comment by pvandriessche** [comment]
I upgraded six and it worked fine

'pip-2.7 install --upgrade six'
