### ISSUE TITLE
troubles with given example

### ISSUE THREAD

**Issue by Guest007** [bennylope/django-organizations#82]
Hi
Python 3.5
Django 1.9b1
Linux

django-organizations - current from github

Ordinar use (just adding organizations in INSTALLED_APPS and migrate) works fine. Invitations and so on
Trying to do ./manage.py migrate in given repo's example with accounts and vendors bring this error to me:

```
$ ./manage.py migrate
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/user/.pyenv/versions/proj/lib/python3.5/site-packages/django/core/management/__init__.py", line 350, in execute_from_command_line
    utility.execute()
  File "/home/user/.pyenv/versions/proj/lib/python3.5/site-packages/django/core/management/__init__.py", line 342, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/user/.pyenv/versions/proj/lib/python3.5/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/user/.pyenv/versions/proj/lib/python3.5/site-packages/django/core/management/base.py", line 398, in execute
    self.check()
  File "/home/user/.pyenv/versions/proj/lib/python3.5/site-packages/django/core/management/base.py", line 426, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/user/.pyenv/versions/proj/lib/python3.5/site-packages/django/core/checks/registry.py", line 75, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/user/.pyenv/versions/proj/lib/python3.5/site-packages/django/core/checks/urls.py", line 10, in check_url_config
    return check_resolver(resolver)
  File "/home/user/.pyenv/versions/proj/lib/python3.5/site-packages/django/core/checks/urls.py", line 19, in check_resolver
    for pattern in resolver.url_patterns:
  File "/home/user/.pyenv/versions/proj/lib/python3.5/site-packages/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/user/.pyenv/versions/proj/lib/python3.5/site-packages/django/core/urlresolvers.py", line 417, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/user/.pyenv/versions/proj/lib/python3.5/site-packages/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/user/.pyenv/versions/proj/lib/python3.5/site-packages/django/core/urlresolvers.py", line 410, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/user/.pyenv/versions/3.5.0/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/user/PP/example/conf/urls.py", line 4, in <module>
    from organizations.backends import invitation_backend, registration_backend
  File "/home/user/.pyenv/versions/proj/src/django-organizations/organizations/backends/__init__.py", line 28, in <module>
    from organizations.app_settings import (ORGS_INVITATION_BACKEND,
  File "/home/user/.pyenv/versions/proj/src/django-organizations/organizations/app_settings.py", line 29, in <module>
    from .utils import model_field_attr
  File "/home/user/.pyenv/versions/proj/src/django-organizations/organizations/utils.py", line 26, in <module>
    from .models import Organization
  File "/home/user/.pyenv/versions/proj/src/django-organizations/organizations/models.py", line 77, in <module>
    class Organization(OrganizationBase, TimeStampedModel):
  File "/home/user/.pyenv/versions/proj/src/django-organizations/organizations/base.py", line 77, in __new__
    model = super(OrgMeta, cls).__new__(cls, name, bases, attrs)
  File "/home/user/.pyenv/versions/proj/lib/python3.5/site-packages/django/db/models/base.py", line 103, in __new__
    "application was loaded. " % (module, name))
RuntimeError: Model class organizations.models.Organization doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. 
```

My goal is to customize organizations model by adding needed fields.

**Comment by spoetnik** [comment]
Add 'organizations' to installed apps.
